services:
  semantic-data-catalog-frontend:
    build: ./frontend
    container_name: semantic_data_catalog_frontend
    volumes:
      - "./frontend:/app/frontend:delegated"
      - "/app/frontend/node_modules"
    stdin_open: true
    environment:
      - REACT_APP_OIDC_ISSUER=https://solidcommunity.net
    depends_on:
      - semantic-data-catalog-backend
    tty: true
    ports:
      - "5000:5000"

  semantic-data-catalog-backend:
    build: ./backend
    container_name: semantic_data_catalog_backend
    environment:
      CATALOG_SERVICE_WEBID: ${CATALOG_SERVICE_WEBID:-https://solid-community-server.tmdt.info/solidservice/profile/card#me}
      CATALOG_SERVICE_OIDC_ISSUER: ${CATALOG_SERVICE_OIDC_ISSUER:-https://solid-community-server.tmdt.info}
      CATALOG_SERVICE_CLIENT_ID: ${CATALOG_SERVICE_CLIENT_ID:-}
      CATALOG_SERVICE_CLIENT_SECRET: ${CATALOG_SERVICE_CLIENT_SECRET:-}
      CATALOG_SERVICE_TOKEN_URL: ${CATALOG_SERVICE_TOKEN_URL:-}
    ports:
      - "8000:8000"

volumes:
  node_modules:
